name: work
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - pip
  - scikit-learn
  - pip
  - jupyter
  - jupyterlab
  - matplotlib
  - seaborn
  - sqlalchemy
  - requests
  - regex
  - yaml
